# Generated by Django 4.0.3 on 2024-05-08 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='P1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Q1', models.CharField(max_length=200)),
                ('req', models.TextField()),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='P2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res', models.TextField()),
                ('time', models.DateTimeField()),
                ('Qu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.p1')),
            ],
        ),
    ]
